--SQL SHORTS

SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME , DEPARTMENT_ID
FROM DEPARTMENTS;

SELECT DEPARTMENT_NAME , DEPARTMENT_ID 
FROM DEPARTMENTS;

SELECT *
FROM DEPARTMENTS , EMPLOYEES;

SELECT EMPLOYEES.EMPLOYEE_ID, DEPARTMENTS.DEPARTMENT_ID
FROM DEPARTMENTS , EMPLOYEES;

/*
DISTINCT keyword : it displays the result without the duplicates
*/

SELECT DISTINCT DEPARTMENT_ID
FROM DEPARTMENTS;

SELECT DISTINCT SALARY
FROM EMPLOYEES;

SELECT DISTINCT MAX_SALARY FROM JOBS;

---WHERE CLAUSE, IN AND BETWEEN STATEMENTS

SELECT *
FROM EMPLOYEES
WHERE SALARY < 5000;

SELECT *
FROM EMPLOYEES
WHERE SALARY < 5000 AND MANAGER_ID = 114;

/*
BETWEEN STATEMENT: used for specifyting the range of the condition
                                            value between low and high
*/

SELECT *
FROM DEPARTMENTS
WHERE LOCATION_ID BETWEEN 1800 AND 2400;

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 3500 AND 5000;


/*
IN STATEMENT: used for specifying the range of the condtion
*/

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (60 , 110 , 30);

SELECT *
FROM COUNTRIES
WHERE REGION_ID IN (1 , 4);


---ORDER BY STATEMENT: used for sorting the result

SELECT *
FROM COUNTRIES
ORDER BY REGION_ID;---by default sorts in ascending order

SELECT *
FROM COUNTRIES
WHERE REGION_ID < 5
ORDER BY REGION_ID ASC;

SELECT *
FROM COUNTRIES
ORDER BY REGION_ID DESC;


---LIKE STATEMENT: partial search (WildCard)

--starts with: 'Chars%'
SELECT COUNT(COUNTRY_NAME)
FROM COUNTRIES
WHERE COUNTRY_NAME LIKE 'Au%';

--ends with: '%chars'
SELECT COUNT(COUNTRY_NAME)
FROM COUNTRIES
WHERE COUNTRY_NAME LIKE '%a';

--starts with & ends with:
SELECT *
FROM COUNTRIES
WHERE COUNTRY_NAME LIKE 'A%' AND COUNTRY_NAME LIKE '%a';

---contains: '%chars%'
SELECT COUNTRY_NAME
FROM COUNTRIES
WHERE COUNTRY_NAME LIKE '%b%';


---TEXT FUNCTIONS
--ONLY USED TO DISPLAY DATA, DOES NOT MPDIFY THE TABLE

--CONCATENATION OPERATOR ||:
SELECT EMAIL || '@gmail.com' FROM EMPLOYEES;

SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES;

---CONCAT(VALUE1 , VALUE2)
SELECT CONCAT(EMAIL , '@gmail.com')  FROM EMPLOYEES;

SELECT CONCAT(   CONCAT(FIRST_NAME , ' ' )   ,     LAST_NAME)     FROM EMPLOYEES;

---UPPER(VALUE)
SELECT UPPER(FIRST_NAME) FROM EMPLOYEES;

--LOWER(VALUE)
SELECT LOWER(FIRST_NAME) FROM EMPLOYEES;

--INITCAP(VALUE) - FIRST LETTER CAPITAL, REST LOWER
SELECT INITCAP(EMAIL) FROM EMPLOYEES;

--LENGTH(VALUE)
SELECT FIRST_NAME , LENGTH(FIRST_NAME) FROM EMPLOYEES;

--REPLACE(COLUMN_NAME , OLD_VALUE, NEW_VALUE)
SELECT FIRST_NAME FROM EMPLOYEES;
SELECT REPLACE(FIRST_NAME , 'e' , 'E')    FROM EMPLOYEES;


--SUBSTR(COLUMN_NAME , BEG_INDEX , END_INDEX)
SELECT FIRST_NAME , SUBSTR(FIRST_NAME , 0 , 1)     FROM EMPLOYEES;

SELECT SUBSTR(FIRST_NAME , 0, 1)  ||   SUBSTR(LAST_NAME , 0 , 1)   FROM EMPLOYEES;

--TRIM(VALUE): REMOVES WHITESPACE
SELECT TRIM(CONCAT('             ' , FIRST_NAME)) FROM EMPLOYEES;

